# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('slug', models.SlugField(max_length=100, verbose_name='\u6807\u793a')),
                ('status', models.IntegerField(choices=[(1, '\u542f\u7528'), (0, '\u7981\u7528')], default=0, verbose_name='\u72b6\u6001')),
                ('sort', models.IntegerField(default=100, verbose_name='\u6392\u5e8f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u9875\u9762\u6807\u9898')),
                ('slug', models.SlugField(max_length=100, verbose_name='\u6807\u793a')),
                ('content', models.TextField(null=True, verbose_name='\u9875\u9762\u5185\u5bb9')),
                ('author', models.CharField(max_length=20, verbose_name='\u4f5c\u8005')),
                ('status', models.IntegerField(choices=[(1, '\u53d1\u5e03'), (0, '\u8349\u7a3f')], default=0, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9875\u9762',
                'verbose_name_plural': '\u9875\u9762',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('slug', models.SlugField(max_length=100, verbose_name='\u6807\u793a')),
                ('image', models.ImageField(null=True, upload_to=b'', verbose_name='\u56fe\u7247')),
                ('description', models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u63cf\u8ff0')),
                ('content', models.TextField(null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('author', models.CharField(max_length=20, verbose_name='\u4f5c\u8005')),
                ('status', models.IntegerField(choices=[(1, '\u53d1\u5e03'), (0, '\u8349\u7a3f')], default=0, verbose_name='\u72b6\u6001')),
                ('view_count', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u6b21\u6570')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
