# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
    ]
