# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(help_text='\u6587\u7ae0\u63cf\u8ff0\u53ef\u4ee5\u4e3a\u7a7a', max_length=1000, verbose_name='\u6587\u7ae0\u63cf\u8ff0'),
        ),
    ]
